message: active profile 'default'

server:
  port: 8080
  max-http-header-size: 10485760
  servlet:
    context-path: /scanner

management:
  server.port: 9080
  endpoints:
    web:
      exposure:
        include: '*'


spring:
  #https://stackoverflow.com/questions/77405977/cannot-invoke-org-hibernate-engine-jdbc-spi-sqlexceptionhelper-convertjava-sql
  #verify in docker run env, from here:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  #to here
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?current_schema=port_scanner
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 10
  rabbitmq:
    username: user
    password: password

logging:
  level:
    root: INFO
    com.ian.davidson.port.scanner.async: DEBUG

scanner:
  time-out: 200
  thread-pool-core: 10
  thread-pool-max: 40
  thread-name-prefix: scanner-async-
  queue-size: 500



rabbit:
  queue-name: queue
  topic-name-dispatch: dispatch
