message: active profile 'default'

server:
  port: 8080
  max-http-header-size: 10485760
  servlet:
    context-path: /scanner

management:
  server.port: 9080
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?current_schema=port_scanner
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 10
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
  rabbitmq:
    username: user
    password: password

logging:
  level:
    root: INFO

scanner:
  time-out: 200
  thread-pool-size: 40

#rabbit:
#
#  dispatch-queue-name: dispatch
